import { HeaderMobile }  from "../../../src/components/mobile/HeaderMobile";
import Head from "next/head";
import { SyntheticEvent } from 'react';


export default function Contact() {
        // client side validation. Good 
        // refactor opportunity with server actions with next.js 14
    const handleSubmit = async (e)=> {
      console.log(e)
      e.preventDefault()
    // do some miner client side validation and then do the rest on the backend,
      const  rawFormData = {
            Name: String(e.target.Name.value), 
            email: String(e.target.email.value),
            location: String(e.target.location.value), 
            message: String(e.target.message.value), 
        }
      const response = await fetch("/api/email",{
            method:'POST',
            body:JSON.stringify(rawFormData),
          }
        );
      const resJSON = await response.json();
        console.log("client",rawFormData, "server",resJSON) 
    } 
 return (
    <>
      <Head>
        <title>Hoobler Inspections</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeaderMobile/> 
      </div>
      <main>
   <div className="max-w-md mx-auto mt-8 p-6 bg-gray-100 rounded-md shadow-md">
      <h2 className="text-2xl font-sans  mb-4">Contact Us</h2>
      <form onSubmit={handleSubmit}>
        <div className="mb-4">
          <label htmlFor="Name" className="block text-sm  font-sans font-medium text-gray-600">
            Name
          </label>
          <input
            type="text"
            id="Name"
            name="Name"
            className="mt-1 p-2 w-full font-sans border rounded-md"
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="email" className="block text-sm font-sans font-medium text-gray-600">
            Email
          </label>
          <input
            type="email"
            id="email"
            name="email"
            className="mt-1 p-2 w-full font-sans border rounded-md" 
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="location" className="block text-sm font-sans font-medium text-gray-600">
            Location
          </label>
          <input
            type="text"
            id="location"
            name="location"
            className="mt-1 p-2 w-full font-sans border rounded-md"
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="message" className="block text-sm font-sans font-medium text-gray-600">
            Message (Please tell us about what type of property you need inpsected)
          </label>
          <textarea
            id="message"
            name="message"
            rows={4}
            className="mt-1 p-2 w-full font-sans border rounded-md"
            required
          ></textarea>
        </div>
        <div className="mt-4">
          <button
            type="submit"
            className="px-4 py-2 bg-blue-500  font-sans text-white rounded-md hover:bg-blue-600"
          >
            Submit
          </button>
        </div>
      </form>
    </div>
      </main>
  </>
  )

  }

