import Link from "next/link";
import { HeaderMobile }  from "../../../src/components/mobile/HeaderMobile";
import Head from "next/head";


export default function Contact() {
    
    const formData = new FormData()
        // client side validation. Good 
        // refactor opportunity with server actions with next.js 14
    const handleSubmit = (e)=> {
      e.preventDefault()
      const  rawFormData = {
            firstName: String(e.target.firstName.value), 
            lastName: String(e.target.lastName.value),
            email: String(e.target.email.value),
            location: String(e.target.location.value), 
            message: String(e.target.message.value), 
        }
      console.log(rawFormData) 
  } 
 return (
    <>
      <Head>
        <title>Hoobler Inspections</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeaderMobile/> 
      </div>
      <main>
   <div className="max-w-md mx-auto mt-8 p-6 bg-gray-100 rounded-md shadow-md">
      <h2 className="text-2xl font-sans  mb-4">Contact Us</h2>
      <form onSubmit={handleSubmit}>
        <div className="mb-4">
          <label htmlFor="firstName" className="block text-sm  font-sans font-medium text-gray-600">
            First Name
          </label>
          <input
            type="text"
            id="firstName"
            name="firstName"
            className="mt-1 p-2 w-full font-sans border rounded-md"
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="lastName" className="block text-sm font-sans ont-medium text-gray-600">
            Last Name
          </label>
          <input
            type="text"
            id="lastName"
            name="lastName"
            className="mt-1 p-2 w-full border font-sans rounded-md"
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="email" className="block text-sm font-sans font-medium text-gray-600">
            Email
          </label>
          <input
            type="email"
            id="email"
            name="email"
            className="mt-1 p-2 w-full font-sans border rounded-md" 
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="location" className="block text-sm font-sans font-medium text-gray-600">
            Location
          </label>
          <input
            type="text"
            id="location"
            name="location"
            className="mt-1 p-2 w-full font-sans border rounded-md"
            required
          />
        </div>
        <div className="mb-4">
          <label htmlFor="message" className="block text-sm font-sans font-medium text-gray-600">
            Message (Please tell us about what type of property you need inpsected)
          </label>
          <textarea
            id="message"
            name="message"
            rows="4"
            className="mt-1 p-2 w-full font-sans border rounded-md"
            required
          ></textarea>
        </div>
        <div className="mt-4">
          <button
            type="submit"
            className="px-4 py-2 bg-blue-500  font-sans text-white rounded-md hover:bg-blue-600"
          >
            Submit
          </button>
        </div>
      </form>
    </div>
      </main>
  </>
  )

  }

