import Head from "next/head";
import Link from "next/link";
import Image from 'next/image';
import { FaHelmetSafety } from "react-icons/fa6";
import { BiSolidMessageRounded } from "react-icons/bi"

export default function Home() {
  let imageHeight = 400
  let imageWidth = 300
  const messageIconSize = 36
  const handleClick = () => {console.log("do somthing")};
    if (typeof window !== "undefined") {
    console.log(window.innerWidth)
    imageWidth =  Math.round(window.innerWidth/2.5)
    imageHeight = window.innerHeight
  }

  return (
    <>
      <Head>
        <title>Hoobler Inspections</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sm:hidden flex mt-2 mr-1 justify-end">
          <BiSolidMessageRounded
            size={messageIconSize}
            onClick={handleClick}
            style={{ color: 'green', }}
          />
        </div>
      <main className="min-h-screen flex-col justify-center  bg-slate-50">
        <div className="flex justify-center">
          <div className="sm:hidden">
            <FaHelmetSafety  size={imageWidth} />
          </div>
          <Image
            className=" hidden sm:hidden" 
            height={imageHeight}
            width={imageWidth}
            src="/alichase.jpeg"
            alt="logo"
          />
        </div>
      </main>
    </>
  );
}
