import Head from "next/head";
import Link from "next/link";
import Image from 'next/image';
import { FaHelmetSafety } from "react-icons/fa6";
import { BiSolidMessageRounded } from "react-icons/bi"
import { HeaderMobile }  from "../../src/components/mobile/HeaderMobile";
import { emitKeypressEvents } from "readline";
import { CbusImageBtn } from "../../src/components/mobile/columbusImageBtn";

export default function Home() {
  let imageHeight = 400
  let imageWidth = 100
 
    if (typeof window !== "undefined") {
      imageWidth =  Math.round(window.innerWidth/2)
      imageHeight = window.innerHeight
      console.log(window.innerWidth, imageWidth)
    }

  return (
    <>
      <Head>
        <title>Hoobler Inspections</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full bg-slate-50 justify-between">
        <HeaderMobile/> 
      </div>
      <main className="min-h-screen flex-col justify-center  bg-slate-50">
       <div className="flex justify-center">
          <div className="sm:hidden">
            <FaHelmetSafety  size={imageWidth} />
          </div>
          <div className="sm:hidden">
            <CbusImageBtn/>  
          </div>
          <Image
            className=" hidden sm:hidden" 
            height={imageHeight}
            width={imageWidth}
            src="/alichase.jpeg"
            alt="logo"
          />
        </div>
      </main>
    </>
  );
}
